
services:

  auto-prompt:
    image: registry.cn-shenzhen.aliyuncs.com/tokengo/console
    ports:
      - 10426:8080
    environment:
      - TZ=Asia/Shanghai
      - DEFAULT_USERNAME=admin # 默认管理员账户
      - DEFAULT_PASSWORD=admin123 # 默认管理员账户
      - API_KEY=ollama # 替换为您的API密钥
      - OpenAIEndpoint=https://host.docker.internal:11434/v1 # OpenAI API端点
      - SCORE_MODEL=qwen3:8b
      - CHAT_MODEL=qwen3:8b,qwen3:14b
      - DEFAULT_CHAT_MODEL=qwen3:8b
      - ConnectionStrings:Type=sqlite
      - ConnectionStrings:Default=Data Source=/app/data/ConsoleService.db
    volumes:
      - data-autoprompt:/app/data
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - agents

  prompt-optimizer:
    image: linshen/prompt-optimizer
    restart: always
    ports:
      - 10427:80
    environment:
      - TZ=Asia/Shanghai
      - ACCESS_USERNAME=admin 
      - ACCESS_PASSWORD=admin123 

  n8n:
    image: docker.n8n.io/n8nio/n8n
    restart: always
    ports:
      - '15678:5678'
    volumes:
      - data-n8n:/home/node/.n8n


volumes:
  data-autoprompt:
    driver: local
  data-n8n:
    driver: local

networks:
  agents:
    driver: bridge

