
services:
  openhands-app:
    image: docker.all-hands.dev/all-hands-ai/openhands:0.39
    container_name: openhands-app
    restart: always
    ports:
      - '10003:3000'
    environment:
      - SANDBOX_RUNTIME_CONTAINER_IMAGE:docker.all-hands.dev/all-hands-ai/runtime:0.39-nikolaik
      - LOG_ALL_EVENTS:true
    volumes:
      - data-openhands:/.openhands-state
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - agents


volumes:
  data-openhands:
    driver: local

networks:
  agents:
    driver: bridge

