services:

  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    restart: always
    ports:
      - '15678:5678'
    volumes:
      - data-n8n:/home/node/.n8n
    networks:
      - flow

volumes:
  data-n8n:
    driver: local

networks:
  flow:
    driver: bridge

